export type CharacterSlot = { id: string; name: string; character: Record<string, unknown>; runtime: Record<string, unknown> | null; updatedAt: string };
const ROSTER_KEY="runeterra-frp-characters"; const ACTIVE_KEY="runeterra-frp-active-character";
export function newCharacterId(){return globalThis.crypto?.randomUUID?.()??`hero-${Date.now()}-${Math.random().toString(36).slice(2)}`}
export function readCharacterSlots():CharacterSlot[]{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(ROSTER_KEY)??"[]")}catch{return[]}}
export function activeCharacterId(){return typeof window==="undefined"?null:localStorage.getItem(ACTIVE_KEY)}
export function upsertCharacterSlot(character:Record<string,unknown>,runtime:Record<string,unknown>|null=null){if(typeof window==="undefined")return;const id=String(character.id||newCharacterId());character={...character,id};const slots=readCharacterSlots();const old=slots.find((slot)=>slot.id===id);const slot:CharacterSlot={id,name:String(character.name||"İsimsiz Maceracı"),character,runtime:runtime??old?.runtime??null,updatedAt:new Date().toISOString()};localStorage.setItem(ROSTER_KEY,JSON.stringify([...slots.filter((entry)=>entry.id!==id),slot]));localStorage.setItem(ACTIVE_KEY,id);localStorage.setItem("runeterra-frp-character",JSON.stringify(character));if(slot.runtime)localStorage.setItem("runeterra-frp-runtime",JSON.stringify(slot.runtime));}
export function activateCharacter(id:string){const slot=readCharacterSlots().find((entry)=>entry.id===id);if(!slot)return false;localStorage.setItem(ACTIVE_KEY,id);localStorage.setItem("runeterra-frp-character",JSON.stringify(slot.character));if(slot.runtime)localStorage.setItem("runeterra-frp-runtime",JSON.stringify(slot.runtime));else localStorage.removeItem("runeterra-frp-runtime");return true}
export function removeCharacter(id:string){const next=readCharacterSlots().filter((entry)=>entry.id!==id);localStorage.setItem(ROSTER_KEY,JSON.stringify(next));if(activeCharacterId()===id){localStorage.removeItem(ACTIVE_KEY);localStorage.removeItem("runeterra-frp-character");localStorage.removeItem("runeterra-frp-runtime");}}
export function importCharacterSlot(value:unknown){const raw=value as {character?:Record<string,unknown>;runtime?:Record<string,unknown>};const character=(raw?.character??value) as Record<string,unknown>;if(!character||typeof character!=="object"||!character.name)throw new Error("Geçerli karakter verisi bulunamadı.");const copy={...character,id:newCharacterId()};upsertCharacterSlot(copy,raw?.runtime??null);return copy.id as string}
