export const progression: Record<string, string[]> = {
  savasci: ["Efor ve Manevralar", "Atılım", "Uzmanlık", "Yetenek Artışı", "Ek Saldırı", "Uzmanlık II", "Sarsılmaz", "Yetenek Artışı", "Efor d8", "Uzmanlık III", "Üçüncü Saldırı", "Yetenek Artışı", "Efor d10", "Uzmanlık IV", "İkinci Atılım", "Yetenek Artışı", "Efor d12", "Uzmanlık V", "Yetenek Artışı", "Savaşın Efendisi"],
  duzenbaz: ["Momentum ve Hassas Darbe", "Kurnaz Eylem", "Uzmanlık", "Yetenek Artışı", "Hassas Darbe 2d6", "Uzmanlık II", "Kaçınma", "Yetenek Artışı", "Hassas Darbe 3d6", "Uzmanlık III", "Hassas Darbe 4d6", "Yetenek Artışı", "Güvenilir Yetenek", "Uzmanlık IV", "Dokunulmaz Adım", "Yetenek Artışı", "Hassas Darbe 6d6", "Uzmanlık V", "Yetenek Artışı", "Kusursuz Fırsat"],
  avci: ["Odak ve Av İşareti", "Avcı Teknikleri", "Uzmanlık", "Yetenek Artışı", "Ek Saldırı", "Uzmanlık II", "Arazi Ustası", "Yetenek Artışı", "Üstün İz", "Uzmanlık III", "Kesintisiz Av", "Yetenek Artışı", "Yırtıcı Sezgi", "Uzmanlık IV", "Avın Sonu", "Yetenek Artışı", "Efsanevi Avcı", "Uzmanlık V", "Yetenek Artışı", "İlk Avcı"],
  buyucu: ["Büyü Kullanımı", "Büyü Yenileme", "Uzmanlık", "Yetenek Artışı", "3. derece büyü", "Uzmanlık II", "Karşı Büyü", "Yetenek Artışı", "5. derece büyü", "Uzmanlık III", "6. derece büyü", "Yetenek Artışı", "7. derece büyü", "Uzmanlık IV", "8. derece büyü", "Yetenek Artışı", "9. derece büyü", "Uzmanlık V", "Yetenek Artışı", "Başbüyücü"],
  ruhban: ["Lütuf ve Dualar", "İnanç Kanalı", "Uzmanlık", "Yetenek Artışı", "Güçlü Dua", "Uzmanlık II", "Sarsılmaz İnanç", "Yetenek Artışı", "Lütuf Artışı", "Uzmanlık III", "Büyük Dua", "Yetenek Artışı", "İlahi Direnç", "Uzmanlık IV", "Yenilmez İrade", "Yetenek Artışı", "Efsanevi Dua", "Uzmanlık V", "Yetenek Artışı", "İnancın Sesi"],
  mucit: ["Yük ve Cihazlar", "Hızlı Kurulum", "Uzmanlık", "Yetenek Artışı", "Gelişmiş Cihaz", "Uzmanlık II", "Alan Onarımı", "Yetenek Artışı", "Yük Artışı", "Uzmanlık III", "Usta Cihaz", "Yetenek Artışı", "Kusursuz Prototip", "Uzmanlık IV", "Zincirleme Cihaz", "Yetenek Artışı", "Efsanevi İcat", "Uzmanlık V", "Yetenek Artışı", "Büyük Mucit"],
  "dovus-ustasi": ["Ritim ve Kombolar", "Akış Adımı", "Uzmanlık", "Yetenek Artışı", "Ek Saldırı", "Uzmanlık II", "Dingin Zihin", "Yetenek Artışı", "Ritim Ustalığı", "Uzmanlık III", "Üçlü Kombo", "Yetenek Artışı", "Beden Kalesi", "Uzmanlık IV", "Boşluk Adımı", "Yetenek Artışı", "Kusursuz Akış", "Uzmanlık V", "Yetenek Artışı", "Tek Nefes"],
  yeminli: ["Azim ve Yemin Darbesi", "Koruyucu Aura", "Uzmanlık", "Yetenek Artışı", "Ek Saldırı", "Uzmanlık II", "Sarsılmaz Yemin", "Yetenek Artışı", "Güçlü Aura", "Uzmanlık III", "Arındırıcı Darbe", "Yetenek Artışı", "Yemin Zırhı", "Uzmanlık IV", "Son Siper", "Yetenek Artışı", "Efsanevi Yemin", "Uzmanlık V", "Yetenek Artışı", "Yaşayan Yemin"],
  ozan: ["İlham ve Ezgiler", "Doğaçlama", "Uzmanlık", "Yetenek Artışı", "Güçlü İlham", "Uzmanlık II", "Karşı Ezgi", "Yetenek Artışı", "İlham Artışı", "Uzmanlık III", "Büyük Sahne", "Yetenek Artışı", "Unutulmaz Nakarat", "Uzmanlık IV", "Kesintisiz Ritim", "Yetenek Artışı", "Efsanevi Ezgi", "Uzmanlık V", "Yetenek Artışı", "Dünyanın Şarkısı"],
  antlasmali: ["Mühür ve Pakt Gücü", "Bedelli Güç", "Uzmanlık", "Yetenek Artışı", "Gelişmiş Pakt", "Uzmanlık II", "Karanlık Direnç", "Yetenek Artışı", "Mühür Ustalığı", "Uzmanlık III", "Derin Antlaşma", "Yetenek Artışı", "Bedeli Reddet", "Uzmanlık IV", "Pakt Kapısı", "Yetenek Artışı", "Efsanevi Antlaşma", "Uzmanlık V", "Yetenek Artışı", "Efendisiz Güç"],
  "sekil-degistirici": ["Vahşet ve Dönüşüm", "Yırtıcı Hamle", "Uzmanlık", "Yetenek Artışı", "Ek Saldırı", "Uzmanlık II", "Uyumlu Beden", "Yetenek Artışı", "Gelişmiş Biçim", "Uzmanlık III", "Çifte Doğa", "Yetenek Artışı", "Ölümsüz İçgüdü", "Uzmanlık IV", "Tepe Yırtıcı", "Yetenek Artışı", "Efsanevi Biçim", "Uzmanlık V", "Yetenek Artışı", "İlk Biçim"],
  cagirici: ["Komuta ve Yoldaş", "Bağlı Emir", "Uzmanlık", "Yetenek Artışı", "Gelişmiş Yoldaş", "Uzmanlık II", "Paylaşılan Duyu", "Yetenek Artışı", "Komuta Artışı", "Uzmanlık III", "İkinci Tezahür", "Yetenek Artışı", "Bağ Kalkanı", "Uzmanlık IV", "Toplu Emir", "Yetenek Artışı", "Efsanevi Yoldaş", "Uzmanlık V", "Yetenek Artışı", "Lejyonun Sesi"],
};

export const advancementLevels = [4, 8, 12, 16, 19];
export function abilityTier(level: number) { return level >= 16 ? 4 : level >= 12 ? 3 : level >= 8 ? 2 : level >= 4 ? 1 : 0; }
export function tierFromText(tier: string) { if (tier.includes("IV")) return 4; if (tier.includes("III")) return 3; if (tier.includes("II")) return 2; return 1; }

export const skillBranches: Record<string, { name: string; keywords: string[] }[]> = {
  savasci: [{ name: "Silah Ustalığı", keywords: ["saldırı", "fiziksel", "silah", "darbe"] }, { name: "Öncülük", keywords: ["müttefik", "koru", "kalkan", "hasarı azalt"] }, { name: "Sarsılmazlık", keywords: ["direnç", "geçici cp", "dayan", "iyileş"] }],
  duzenbaz: [{ name: "Gölge", keywords: ["gizli", "görünmez", "gölge", "karanlık"] }, { name: "Hareket", keywords: ["hareket", "ışınlan", "atıl", "hız"] }, { name: "Hassasiyet", keywords: ["kritik", "tek hedef", "işaret", "isabet"] }],
  avci: [{ name: "Av", keywords: ["işaret", "hedef", "iz", "ok", "menzilli"] }, { name: "Doğa", keywords: ["doğa", "hayvan", "zehir", "arazi"] }, { name: "Ruh Bağı", keywords: ["ruh", "çağır", "yoldaş", "iyileş"] }],
  buyucu: [{ name: "Element", keywords: ["ateş", "soğuk", "yıldırım", "element", "enerji"] }, { name: "Rün", keywords: ["rün", "büyü", "ark", "söküm"] }, { name: "Kontrol", keywords: ["kurtarma", "alan", "yoğunlaşma", "yanılsama"] }],
  ruhban: [{ name: "Şifa", keywords: ["iyileş", "cp kazan", "şifa", "arındır"] }, { name: "Koruma", keywords: ["koru", "direnç", "kalkan", "hasarı azalt"] }, { name: "Ruh", keywords: ["ruh", "ışık", "ölüm", "müttefik"] }],
  mucit: [{ name: "Hextech", keywords: ["enerji", "ışınlan", "kalkan", "teknoloji"] }, { name: "Kimya", keywords: ["zehir", "asit", "iyileş", "karışım"] }, { name: "Düzenek", keywords: ["bomba", "tuzak", "alan", "cihaz"] }],
  "dovus-ustasi": [{ name: "Ruh Yumruğu", keywords: ["darbe", "ruh", "sersem", "it"] }, { name: "Akış", keywords: ["hareket", "atıl", "hız", "kaçın"] }, { name: "Kombo", keywords: ["saldırı", "isabet", "kritik", "yakın"] }],
  yeminli: [{ name: "Muhafaza", keywords: ["koru", "kalkan", "müttefik", "direnç"] }, { name: "Hüküm", keywords: ["ışık", "hasar", "işaret", "saldırı"] }, { name: "Yemin", keywords: ["cesaret", "arın", "korku", "iyileş"] }],
  ozan: [{ name: "İlham", keywords: ["müttefik", "zar", "iyileş", "cesaret"] }, { name: "Sahne", keywords: ["alan", "ses", "büyülen", "korku"] }, { name: "Ritim", keywords: ["hareket", "hız", "tepki", "saldırı"] }],
  antlasmali: [{ name: "Lanet", keywords: ["lanet", "işaret", "ölüm", "gölge"] }, { name: "Pakt", keywords: ["ruh", "büyü", "karanlık", "çağır"] }, { name: "Bedel", keywords: ["can", "hasar", "direnç", "dönüş"] }],
  "sekil-degistirici": [{ name: "Yırtıcı", keywords: ["pençe", "ısır", "saldırı", "hareket"] }, { name: "Yaban", keywords: ["doğa", "hayvan", "arazi", "duyu"] }, { name: "Dönüşüm", keywords: ["biçim", "dönüş", "direnç", "iyileş"] }],
  cagirici: [{ name: "Yoldaş", keywords: ["yoldaş", "hayvan", "müttefik", "koru"] }, { name: "Tezahür", keywords: ["çağır", "ruh", "gölge", "yaratık"] }, { name: "Komuta", keywords: ["hedef", "hareket", "saldırı", "alan"] }],
};
