"use client";
import { useEffect,useRef,useState } from "react";
import Link from "next/link";
import { Copy,Download,FileUp,Pencil,Plus,Printer,Shield,Trash2 } from "lucide-react";
import { activateCharacter,importCharacterSlot,newCharacterId,readCharacterSlots,removeCharacter,upsertCharacterSlot,type CharacterSlot } from "@/lib/character-storage";
export function CharacterManager(){const[slots,setSlots]=useState<CharacterSlot[]>([]);const input=useRef<HTMLInputElement>(null);const refresh=()=>setSlots(readCharacterSlots().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));useEffect(refresh,[]);
  function open(id:string,href:string){activateCharacter(id);window.location.href=href}
  function duplicate(slot:CharacterSlot){const character={...slot.character,id:newCharacterId(),name:`${slot.name} — Kopya`};upsertCharacterSlot(character,slot.runtime?structuredClone(slot.runtime):null);refresh()}
  function remove(slot:CharacterSlot){if(window.confirm(`${slot.name} kalıcı olarak silinsin mi? Bu işlem geri alınamaz.`)){removeCharacter(slot.id);refresh()}}
  function download(slot:CharacterSlot){const blob=new Blob([JSON.stringify({system:"Runeterra FRP",version:"0.8.0",character:slot.character,runtime:slot.runtime},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${slot.name}.json`;a.click();URL.revokeObjectURL(a.href)}
  async function upload(file?:File){if(!file)return;try{importCharacterSlot(JSON.parse(await file.text()));refresh()}catch(error){alert(error instanceof Error?error.message:"Dosya alınamadı.")}if(input.current)input.current.value=""}
  return <main className="character-manager shell"><header><div><p className="eyebrow">Kahraman kasası</p><h1>Karakterlerim</h1><p>Karakterlerini seç, düzenle, kopyala, arşivle veya yazdır.</p></div><div><Link className="button button-primary" href="/karakter?new=1"><Plus size={16}/> Yeni karakter</Link><button className="button button-ghost" onClick={()=>input.current?.click()}><FileUp size={16}/> JSON içe aktar</button><input ref={input} hidden type="file" accept="application/json" onChange={(event)=>upload(event.target.files?.[0])}/></div></header>{slots.length?<section className="character-slot-grid">{slots.map((slot)=>{const character=slot.character as {level?:number;classId?:string;concept?:string};return <article key={slot.id}><div className="slot-seal"><Shield size={25}/></div><small>Seviye {character.level??1} · {character.classId||"Sınıfsız"}</small><h2>{slot.name}</h2><p>{character.concept||"Karakter fikri yazılmamış."}</p><time>{new Date(slot.updatedAt).toLocaleString("tr-TR")}</time><div className="slot-primary"><button onClick={()=>open(slot.id,"/karakter/masa")}>Masayı aç</button><button onClick={()=>open(slot.id,"/karakter")}><Pencil size={14}/> Düzenle</button></div><div className="slot-tools"><button title="Kopyala" onClick={()=>duplicate(slot)}><Copy size={14}/></button><button title="JSON indir" onClick={()=>download(slot)}><Download size={14}/></button><button title="Yazdır" onClick={()=>open(slot.id,"/karakter/yazdir")}><Printer size={14}/></button><button className="danger" title="Sil" onClick={()=>remove(slot)}><Trash2 size={14}/></button></div></article>})}</section>:<section className="manager-empty"><Shield size={45}/><h2>Henüz kayıtlı karakter yok.</h2><p>Yeni bir kahraman oluşturabilir veya daha önce indirdiğin JSON dosyasını içe aktarabilirsin.</p></section>}</main>}
